#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.C64P{1,0,7.2,3
#
app.x64P: package/cfg/app.x64P.mak

clean::
	-$(RM) package/cfg/app.x64P.mak
